# Generated by Django 4.0 on 2022-08-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='flight',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.category'),
        ),
    ]
