# Generated by Django 4.0 on 2022-08-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(default='', upload_to='flights/'),
            preserve_default=False,
        ),
    ]
