# Generated by Django 4.0 on 2022-08-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_flight_price_category_price_flight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('First Class', 'First Class'), ('Economy Class', 'Economy Class')], max_length=200),
        ),
    ]
