# Generated by Django 4.0 on 2022-08-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('drop_off_time', models.TimeField()),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('auto_gear', models.BooleanField()),
                ('number_of_people', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(auto_now_add=True)),
                ('from_time', models.TimeField(auto_now_add=True)),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
    ]
