# Generated by Django 4.0 on 2022-08-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreservation',
            name='number_of_days',
        ),
    ]
